# Generated by Django 5.0.2 on 2024-02-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
