# Generated by Django 5.0.2 on 2024-02-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
